name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag, and push image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: python
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest


  deploy_to_server:
   needs: build
   runs-on: ubuntu-latest
   steps:
      - name: Deploy to Server
        if: success() # Only deploy if the previous steps were successful
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Log in to the Docker Hub
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            # Replace this with your deployment script
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/python:latest
            docker stop python || true  # Stop container if it exists, ignore errors if it doesn't
            docker rm python || true    # Remove container if it exists, ignore errors if it doesn't
            docker run -d -it -p 8080:8080 --name python ${{secrets.DOCKERHUB_USERNAME}}/python

  test_http:
      needs: deploy_to_server
      runs-on: ubuntu-latest
      steps:
      - name: Test HTTP return code
        run: |
          status=$(curl -I 18.136.107.195:8080 2>/dev/null | head -n 1 | cut -d$' ' -f2)
          echo "HTTP return code: $status"
          if [ "$status" == "200" ]; then
            echo "HTTP return code is OK."
          else
            echo "HTTP return code is not OK. Status code: $status"
            exit 1
          fi
